// <auto-generated />
using System;
using ContextMemory.Infrastructure.Persistence.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ContextMemory.Infrastructure.Migrations
{
    [DbContext(typeof(ContextMemoryDbContext))]
    partial class ContextMemoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ContextMemory.Infrastructure.Persistence.Postgres.AgenticPendingRecordEntity", b =>
                {
                    b.Property<string>("AppId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SessionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("StateJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AppId", "UserId", "SessionId");

                    b.ToTable("agentic_pending_records", (string)null);
                });

            modelBuilder.Entity("ContextMemory.Infrastructure.Persistence.Postgres.AppProfileEntity", b =>
                {
                    b.Property<string>("AppId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("BusinessRules")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("FormatRules")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Persona")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WikiSchema")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AppId");

                    b.ToTable("app_profiles", (string)null);
                });

            modelBuilder.Entity("ContextMemory.Infrastructure.Persistence.Postgres.RegisteredAppEntity", b =>
                {
                    b.Property<string>("AppId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AppId");

                    b.ToTable("registered_apps", (string)null);
                });

            modelBuilder.Entity("ContextMemory.Infrastructure.Persistence.Postgres.SessionRecordEntity", b =>
                {
                    b.Property<string>("AppId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SessionId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AppId", "UserId", "SessionId");

                    b.ToTable("session_records", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
